[package]
name = "yaglw"
version = "0.0.0"
authors = [
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Ben Foppa <benjamin.foppa@gmail.com>",
  ]

[lib]
name = "yaglw"
path = "src/lib.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
